import { type NextPage } from "next";
import Head from "next/head";
import { useState, type FormEventHandler } from "react";
import { trpc } from "../utils/trpc";
import { signOut, useSession } from "next-auth/react";
import { useRouter } from "next/router";
import Link from "next/link";

const Project: NextPage = () => {
    const router = useRouter();
    const util = trpc.useContext();
    const [nameproject, setNameproject] = useState("");
    const [description, setDescription] = useState("");
    const { data: projects = [] } = trpc.project.getAll.useQuery();
    const { data: session, status } = useSession();
    const createProject = trpc.project.create.useMutation({
      onSuccess() {
        util.project.invalidate();
        router.push("/project-page");
      },
    });
    
  
    const handleSubmit: FormEventHandler<HTMLFormElement> = async (e) => {
      e.preventDefault();
      await createProject.mutateAsync({ 
        nameproject, 
        description,
      });
      setNameproject("");
      setDescription("");

    };

  
    if (status == "loading") {
      return <p>Loading ...</p>;
    }
    if (status == "unauthenticated") {
      router.push("/login");
      return <p>Access denied!</p>;
    }

    return (
        <>
        <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen items-center justify-center">
        <div className="absolute top-4 right-4">
          Welcome {session?.user?.email}
          <button
            onClick={() => signOut({ callbackUrl: "/login" })}
            className="ml-4 font-semibold text-purple-800 underline underline-offset-2"
          >
            Logout?
          </button>
        </div>
        <div className="mx-auto w-full px-4 py-8 shadow lg:w-1/3">
          <div className="mb-6 flex items-center">
            <h1 className="mr-6 text-4xl font-bold text-purple-600">
              {" "}
              Create Project
            </h1>
          </div>
          <form onSubmit={handleSubmit} className="relative">
            <input
              type="text"
              placeholder="Project Name"
              value={nameproject}
              onChange={(e) => setNameproject(e.target.value)}
              className="border-grey-600 w-full rounded border px-2 py-1 outline-none"
            />
            <input
              type="text"
              placeholder="Description"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              className="border-grey-600 w-full rounded border px-2 py-1 outline-none"
            />
            
            <button className="bg-purple-600 text-white px-4 py-2 rounded shadow">Create Project</button>
          </form>

          <div>
          <ul className="mt-4">
            {projects.map((project) => (
              <li key={project.id} className="flex items-center justify-between border-b px-2 py-6">
              <span className="inline-block text-gray-600">
                {project.nameproject}
              </span>
              <span className="inline-block text-gray-600">
                {project.description}
              </span>

              <div className="absolute right-0 flex items-center space-x-2">
                <button className="bg-purple-600 text-white px-4 py-2 rounded shadow">Project Details</button>
              </div>
            </li>
            ))}
          </ul>
          </div>

        </div>
        </div>
        </>
    );
  };

export default Project;
