import { type NextPage } from "next";
import Head from "next/head";
import { useState, type FormEventHandler } from "react";
import { signOut, useSession } from "next-auth/react";
import { useRouter } from "next/router";
import Link from "next/link";
import { trpc } from "../../../../utils/trpc";

interface Document {
    children: React.ReactNode;
}

const Document = ({ children }: Document) => {
    const util = trpc.useContext();
    const router = useRouter();
    const { data: session, status } = useSession();

    if (status == "loading") {
        return <p>Loading ...</p>;
      }
      if (status == "unauthenticated") {
        router.push("/login");
        return <p>Access denied!</p>;
      }

return (
    <>
    <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
      <div className="flex h-screen items-center justify-center">
        <div className="absolute top-4 right-4">
          Welcome {session?.user?.email}
          <button
            onClick={() => signOut({ callbackUrl: "/login" })}
            className="ml-4 font-semibold text-purple-800 underline underline-offset-2"
          >
            Logout?
          </button>
        </div>
        <div className="mx-auto w-full px-4 py-8 shadow lg:w-1/3">
            {children}
        </div>
        </div>
        </>
    );
};

export default Document;


